INSERT INTO CAFE(ID,nomCafe , CANTIDAD , PRECIO ) VALUES(1999,'Cafe solo', 3,2);
INSERT INTO CAFE(ID,nomCafe , CANTIDAD , PRECIO ) VALUES(2000,'Cafe con leche', 3,2);
INSERT INTO CAFE(ID,nomCafe , CANTIDAD , PRECIO ) VALUES(0,'nulo', 1,1);
INSERT INTO REFRESCO(ID,nomRefresco , CANTIDAD , PRECIO ) VALUES(0,'nulo', 1,1);
-- INSERT INTO CAFE(ID,nomCafe , CANTIDAD , PRECIO ) VALUES(0,'Cafe nulo', 1,1);
-- INSERT INTO REFRESCO(ID,nomRefresco , CANTIDAD , PRECIO ) VALUES(3,'Coca-Cola', 3,2);
-- INSERT INTO BEBIDA(ID,NOMBRE , PRECIO, CAFE_ID , REFRESCO_ID) VALUES(1,'Coca-Cola', 2 , 1,3);
-- INSERT INTO BEBIDA(ID, CAFE_ID , REFRESCO_ID) VALUES(1, 1 ,3);
