INSERT INTO CAFE(ID,NOM_PRODUCTO , CANTIDAD , PRECIO ) VALUES(1,'Cafe solo', 3,2);
-- INSERT INTO CAFE(ID,NOM_PRODUCTO , CANTIDAD , PRECIO ) VALUES(2,'Cafe con leche', 3,2);
-- INSERT INTO REFRESCO(ID,NOM_PRODUCTO , CANTIDAD , PRECIO ) VALUES(3,'Coca-Cola', 3,2);
-- INSERT INTO BEBIDA(ID,NOMBRE , PRECIO, CAFE_ID , REFRESCO_ID) VALUES(1,'Coca-Cola', 2 , 1,3);
