-- Creación de la tabla 'bebida'
CREATE TABLE bebida (
    id INTEGER NOT NULL,
    
    precio FLOAT(53) NOT NULL,
    cafe_id INTEGER,
    refresco_id INTEGER,
    PRIMARY KEY (id)
);

-- Creación de la tabla 'cafe'
CREATE TABLE cafe (
    id INTEGER NOT NULL,
    -- cantidad INTEGER,
    nomcafe VARCHAR(255),
    precio FLOAT(53),
    PRIMARY KEY (id)
);

-- Creación de la tabla 'cliente'
CREATE TABLE cliente (
    id INTEGER NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    logeado BOOLEAN NOT NULL,
    nom_cliente VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Creación de la tabla 'comida'
CREATE TABLE comida (
    id INTEGER NOT NULL,
    nom_comida VARCHAR(255) NOT NULL,
    precio FLOAT(53) NOT NULL,
    PRIMARY KEY (id)
);

-- Creación de la tabla 'consumicion'
CREATE TABLE consumicion (
    id INTEGER NOT NULL,
    nombre_consumicion VARCHAR(255) NOT NULL,
    precio FLOAT(53) NOT NULL,
    cantidad_comida INTEGER NOT NULL,
    cantidad_bebida INTEGER NOT NULL,
    bebida_id INTEGER,
    comida_id INTEGER,
    PRIMARY KEY (id)
);

-- Creación de la tabla 'pedido'
CREATE TABLE pedido (
    num_pedido INTEGER NOT NULL,
    usuario_id INTEGER,
    consumicion_id INTEGER,
    trabajador_id INTEGER,
    PRIMARY KEY (num_pedido)
);

-- Creación de la tabla 'refresco'
CREATE TABLE refresco (
    id INTEGER NOT NULL,
    -- cantidad INTEGER NOT NULL,
    nomrefresco VARCHAR(255),
    precio FLOAT(53) NOT NULL,
    PRIMARY KEY (id)
);

-- Creación de la tabla 'trabajador'
CREATE TABLE trabajador (
    id INTEGER NOT NULL,
    apellidos VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    nombre VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id)
);

-- Creación de la tabla 'usuario'
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    apellidos VARCHAR(255),
    email VARCHAR(255),
    nombre VARCHAR(255),
    password VARCHAR(255),
    PRIMARY KEY (id)
);

-- Creación de secuencias
CREATE SEQUENCE cafe_seq START WITH 70 INCREMENT BY 50;
CREATE SEQUENCE primary_sequence START WITH 70 INCREMENT BY 50;

-- Añadir restricciones de clave externa
ALTER TABLE bebida ADD CONSTRAINT FK3gk5onhtip21b5gr2hyn8gi37 FOREIGN KEY (cafe_id) REFERENCES cafe;
ALTER TABLE bebida ADD CONSTRAINT FKbedvyp6h3u0mhh7ir0gd9nu99 FOREIGN KEY (refresco_id) REFERENCES refresco;
ALTER TABLE consumicion ADD CONSTRAINT FKdak95yst690q7khg2s4fcv2f4 FOREIGN KEY (bebida_id) REFERENCES bebida;
ALTER TABLE consumicion ADD CONSTRAINT FK8gdymlfyw378dr21sboiv2bh FOREIGN KEY (comida_id) REFERENCES comida;
ALTER TABLE pedido ADD CONSTRAINT FKs1mi3w1sljwlytso2ioqdh1i7 FOREIGN KEY (usuario_id) REFERENCES usuario;
ALTER TABLE pedido ADD CONSTRAINT FK9td4y476csbbmggun7jpsxog1 FOREIGN KEY (consumicion_id) REFERENCES consumicion;
ALTER TABLE pedido ADD CONSTRAINT FK7jkms41qkp9oj73n1153hp1w3 FOREIGN KEY (trabajador_id) REFERENCES trabajador;
